[project]
name = "awaz-khata-ai-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ramzan Naveed", email = "ramzannaveed65@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "google-genai>=2.21.0",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]
[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
